name: "Update Manifest on Tag"

on:
  push:
    tags:
      - 'v*' 

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout de la branche main
      - name: Checkout main
        uses: actions/checkout@v4.2.2
        with:
          ref: main

      # Extraire la version depuis le tag
      - name: Set version from tag
        id: vars
        run: |
          TAG="${GITHUB_REF##*/}"       # ex: v1.3.5
          VERSION="${TAG#v}"            # ex: 1.3.5
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Mettre à jour le manifest.json
      - name: Update manifest.json version
        run: |
          yq e -P -o=json -i ".version = \"${VERSION}\"" "custom_components/new_bestway_spa/manifest.json"

      # Commit & push la modification dans main
      - name: Commit & push manifest.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add custom_components/new_bestway_spa/manifest.json
          git commit -m "Update manifest.json version to ${VERSION}" || echo "No changes to commit"
          git push
